title: Sakari Ollikainen # your name (or website title) here
logo: "/images/face 2026-08-27 104235.png?raw=true" # your photo (or logo) here
description: >
  Hey I'm Sakari Ollikainen and here you can find some of my coding projects I've made during my time in University.
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
